# Generated by Django 5.1 on 2024-09-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='university',
            field=models.CharField(choices=[('ulsa', 'La Salle'), ('ana', 'Anahuac'), ('tec', 'Tecnologico de Monterrey'), ('ipn', 'IPN'), ('unam', 'UNAM')], max_length=4, null=True),
        ),
    ]
