# Generated by Django 5.1 on 2024-10-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_posts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_uni', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('pub', 'publica'), ('priv', 'privada')], max_length=4)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
