# Generated by Django 5.1 on 2024-10-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('bancos', 'bancos'), ('seguridad', 'seguridad'), ('comida', 'comida'), ('consejos', 'consejos'), ('alojamiento', 'alojamiento')], default='bancos', max_length=15),
        ),
        migrations.AlterField(
            model_name='posts',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
