# Generated by Django 5.1 on 2024-10-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_posts_type_alter_posts_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='type',
            field=models.CharField(choices=[('bancos', 'bancos'), ('seguridad', 'seguridad'), ('comida', 'comida'), ('consejos', 'consejos'), ('alojamiento', 'alojamiento'), ('otros', 'otros')], default='bancos', max_length=15),
        ),
    ]
