# Generated by Django 5.1 on 2024-10-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_posts_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='banos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='cuartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos/'),
        ),
        migrations.AddField(
            model_name='posts',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
