# Generated by Django 5.1 on 2024-10-17 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_posts_banos_posts_cuartos_posts_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.university'),
        ),
    ]
