# Generated by Django 5.1 on 2024-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_posts_foto_alter_posts_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
