# Generated by Django 5.1 on 2024-10-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='valuation',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
