# Generated by Django 5.1 on 2024-10-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_posts_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
